#logging:
#  pattern:
#    console: "%d - %msg%n"
#  level:
#    com.mooc.SellApplicationTests: info
#配置端口
server:
  port: 8080
  servlet:
    context-path: /sell
#配置数据源
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ssm?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 7820170
  jackson:
    default-property-inclusion: non_null
  freemarker:
    suffix: .ftl
    template-loader-path: classpath:templates/
  redis:
    host: localhost
    port: 6379
    password: 7820170

#配置mybatis
mybatis-plus:
    mapper-locations: classpath:mapping/*Mapper.xml
    type-aliases-package: classpath:com.mooc.entity
    configuration:
      map-underscore-to-camel-case: true
#      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


wechat:
#支付猫自带授权，不需要这个
#  mpAppId: wxe0998069c517da82
#  mpAppSecret: 0582c7a6abb36d7794f37a04e873e777
  mchId: 15725461072007
  mchKey: p5oYS6h0u2u1m5QI7YCVzgZMtV2T94eP


projecturl:
  getOpenIdUrl: https://api.paycats.cn/v1/wx/openid
  prePayUrl: https://api.paycats.cn/v1/pay/wx/jsapi
  refundUrl: https://api.paycats.cn/v1/order/refund
  sellUrl: http://47.103.223.103
#  sellUrl: http://localhost

